name: Cypress health check tests TAT Apps
on:
  push:
    branches:
      - main
  schedule:
    # runs twice a day (at noon and midnight - UTC)
    - cron: '0 12,18,00,06 * * *'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
